2022-11-09 15:04:23,894 - root - DEBUG - Connection active
2022-11-09 15:04:23,900 - root - INFO - Recieved ag.txt
2022-11-09 15:04:23,910 - root - INFO - File ag.txt stored successfully
2022-11-09 15:04:23,911 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:04:23,933 - root - DEBUG - Connection active
2022-11-09 15:04:23,937 - root - INFO - Recieved CMC_Q02_0MATERIAL_ATTR.csv
2022-11-09 15:04:23,948 - root - INFO - File CMC_Q02_0MATERIAL_ATTR.csv stored successfully
2022-11-09 15:04:23,948 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:04:24,021 - root - DEBUG - Connection active
2022-11-09 15:04:24,032 - root - INFO - Recieved CMC_Q02_0PLANT_ATTR.csv
2022-11-09 15:04:24,039 - root - INFO - File CMC_Q02_0PLANT_ATTR.csv stored successfully
2022-11-09 15:04:24,040 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:04:24,367 - root - DEBUG - Connection active
2022-11-09 15:04:24,372 - root - INFO - Recieved CMC_Q02_0PROD_HIER_TEXT.csv
2022-11-09 15:04:24,385 - root - INFO - File CMC_Q02_0PROD_HIER_TEXT.csv stored successfully
2022-11-09 15:04:24,386 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:04:24,580 - root - DEBUG - Connection active
2022-11-09 15:04:24,732 - root - INFO - Recieved CMC_Q02_MARM.csv
2022-11-09 15:04:24,779 - root - INFO - File CMC_Q02_MARM.csv stored successfully
2022-11-09 15:04:24,779 - root - INFO -  [*] Waiting for messages.
2022-11-09 15:04:25,265 - root - ERROR - Connection closed by Broker
2022-11-09 15:04:25,278 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:04:30,298 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-09 15:04:30,303 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\recieve.py", line 138, in main
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.IncompatibleProtocolError: StreamLostError: ('Transport indicated EOF',)

2022-11-09 15:04:30,304 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:04:30,322 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:04:35,334 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:04:39,428 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:04:44,433 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:04:48,528 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:04:53,539 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:04:57,621 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:05:02,632 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:05:06,729 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:05:11,738 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:05:15,831 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:05:20,843 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
