2022-11-09 15:02:28,146 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-09 15:02:28,153 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\recieve.py", line 138, in main
    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 360, in __init__
    self._impl = self._create_connection(parameters, _impl_class)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 451, in _create_connection
    raise self._reap_last_connection_workflow_error(error)
pika.exceptions.AMQPConnectionError

2022-11-09 15:02:28,155 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:02:32,261 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:02:37,272 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:02:41,355 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:02:46,362 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:02:46,379 - root - ERROR - Dev Mode: Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-09 15:02:51,385 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:03:42,139 - root - INFO - Dev Mode: Initiating Connection to RabbitMQ Instance
2022-11-09 15:03:42,150 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
