2022-11-09 15:14:49,366 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:14:54,373 - root - ERROR - Fatal Error
2022-11-09 15:14:54,373 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 250, in main
    if checkConnection() == True:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 124, in checkConnection
    return connect_open
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:14:54,374 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:15:03,489 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:15:08,497 - root - ERROR - Fatal Error
2022-11-09 15:15:08,498 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 250, in main
    if checkConnection() == True:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 124, in checkConnection
    return connect_open
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:15:08,498 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:15:17,605 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:15:22,618 - root - ERROR - Fatal Error
2022-11-09 15:15:22,619 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 250, in main
    if files is not None:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 124, in checkConnection
    logging.error(f"Connection check failed, sleeping {sleepTime} seconds")
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:15:22,620 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:15:31,718 - root - ERROR - Connection check failed, sleeping 5 seconds
2022-11-09 15:15:36,720 - root - ERROR - Fatal Error
2022-11-09 15:15:36,722 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 250, in main
    if files is not None:
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\send.py", line 124, in checkConnection
    logging.error(f"Connection check failed, sleeping {sleepTime} seconds")
UnboundLocalError: local variable 'connect_open' referenced before assignment

2022-11-09 15:15:36,723 - root - INFO - Will Attempt Reconection in 5 seconds
2022-11-09 15:15:41,763 - root - DEBUG - Connection active
2022-11-09 15:15:41,790 - root - INFO - Moved \CMC_Q02_MAT_PLANT_ATTR.csv' to long term storage
2022-11-09 15:15:41,877 - root - DEBUG - Connection active
2022-11-09 15:15:41,903 - root - INFO - Moved \CMC_Q02_TCURR.csv' to long term storage
2022-11-09 15:15:41,985 - root - DEBUG - Connection active
2022-11-09 15:15:42,004 - root - INFO - Moved \dads.txt' to long term storage
2022-11-09 15:15:42,017 - root - DEBUG - Connection active
2022-11-09 15:15:42,034 - root - INFO - Moved \fdsfdsf.txt' to long term storage
2022-11-09 15:15:42,049 - root - DEBUG - Connection active
2022-11-09 15:15:42,066 - root - INFO - Moved \mike.txt' to long term storage
2022-11-09 15:15:42,082 - root - DEBUG - Connection active
2022-11-09 15:15:42,103 - root - INFO - Moved \one.txt' to long term storage
2022-11-09 15:15:42,108 - root - INFO - No new files will check in 5 seconds
2022-11-09 15:15:47,121 - root - INFO - No new files will check in 5 seconds
