2022-11-11 15:14:59,055 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-11 15:14:59,059 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\src\recieve.py", line 126, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 953, in poll
    read, write, error = select.select(
KeyboardInterrupt

2022-11-11 15:14:59,061 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-11 15:14:59,062 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-11 15:14:59,078 - root - INFO - Connection to RabbitMQ sucessful
2022-11-11 15:14:59,078 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-11 15:14:59,079 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-11 15:14:59,094 - root - INFO - Connection to RabbitMQ sucessful
2022-11-11 15:14:59,095 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
2022-11-11 15:15:04,101 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-11 15:15:04,101 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\src\recieve.py", line 126, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 953, in poll
    read, write, error = select.select(
KeyboardInterrupt

2022-11-11 15:15:04,102 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-11 15:15:04,102 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-11 15:15:04,131 - root - INFO - Connection to RabbitMQ sucessful
2022-11-11 15:15:04,132 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-11 15:15:04,132 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-11 15:15:04,149 - root - INFO - Connection to RabbitMQ sucessful
2022-11-11 15:15:04,153 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
2022-11-11 15:15:09,155 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-11 15:15:09,156 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\src\recieve.py", line 126, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 514, in _flush_output
    self._impl.ioloop.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 579, in poll
    self._poller.poll()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\select_connection.py", line 953, in poll
    read, write, error = select.select(
KeyboardInterrupt

2022-11-11 15:15:09,157 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-11 15:15:09,157 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-11 15:15:09,159 - root - ERROR - Connection to RabbitMQ unsucesfull, retying in 5 seconds
2022-11-11 15:15:10,550 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-11 15:15:10,550 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-11 15:15:10,582 - root - INFO - Connection to RabbitMQ sucessful
2022-11-11 15:15:10,584 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
2022-11-11 15:15:28,377 - root - DEBUG - Connection active
2022-11-11 15:15:28,769 - root - INFO - Recieved 15-15-15.csv
2022-11-11 15:15:28,916 - root - INFO - File 15-15-15.csv stored successfully
2022-11-11 15:15:28,916 - root - INFO -  [*] Waiting for messages.
