2022-11-12 02:33:29,734 - root - ERROR - Unknown Connection Failure, network might be down..
2022-11-12 02:33:31,480 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\rfranqui\OneDrive - Entegris\Documents\P\Projects\RabbitMQ\src\recieve.py", line 126, in main
    channel.start_consuming()
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 1883, in start_consuming
    self._process_data_events(time_limit=None)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 2044, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 842, in process_data_events
    self._flush_output(common_terminator)
  File "C:\Users\rfranqui\Miniconda3\lib\site-packages\pika\adapters\blocking_connection.py", line 523, in _flush_output
    raise self._closed_result.value.error
pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 60 seconds

2022-11-12 02:33:31,536 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-12 02:33:31,537 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-12 02:33:32,510 - root - INFO - Connection to RabbitMQ sucessful
2022-11-12 02:33:32,511 - root - INFO - Initiating Connection to RabbitMQ Instance
2022-11-12 02:33:32,512 - root - INFO - Attempting Devmode Connection to RabbitMQ
2022-11-12 02:33:32,807 - root - INFO - Connection to RabbitMQ sucessful
2022-11-12 02:33:32,839 - root - INFO -  [*] Waiting for messages. To exit press CTRL+C
